import { randomUUID } from 'node:crypto';

import pinoHttp from 'pino-http';

import type { Request, Response } from 'express';
import { logger } from '@/config/logger';
import { HttpStatusCode } from '@/core/AppError';

/**
 * HTTP request logging middleware.
 *
 * Purpose:
 * - Creates/propagates a request correlation ID.
 * - Records request outcome and duration.
 * - Correlates HTTP logs with application/database logs through AsyncLocalStorage.
 *
 * ID semantics:
 * - traceId: identifies the distributed request/trace across services.
 * - requestId: identifies this HTTP request within the current service.
 *
 * The middleware intentionally does not serialize the full request/response
 * objects to avoid accidental logging of headers, cookies, bodies, or PII.
 */
export const requestLogger = pinoHttp<Request, Response>({
  logger,

  /**
   * pino-http's internal request ID.
   *
   * Prefer the request-scoped requestId generated by trace middleware.
   * Fall back to traceId, then generate a new UUID only as a last resort.
   */
  genReqId: (req) => req.requestId ?? req.traceId ?? randomUUID(),

  /**
   * Map HTTP outcome to an appropriate log level.
   */
  customLogLevel(_req, res, err) {
    if (err || res.statusCode >= HttpStatusCode.INTERNAL_SERVER_ERROR) {
      return 'error';
    }

    if (res.statusCode >= HttpStatusCode.BAD_REQUEST) {
      return 'warn';
    }

    return 'info';
  },

  /**
   * Avoid noisy access logs for infrastructure probes and static requests.
   */
  autoLogging: {
    ignore: (req) => {
      const url = req.url.split('?')[0];
      return ['/health', '/ping', '/favicon.ico'].includes(url ?? '');
    },
  },

  /**
   * Add only intentionally selected fields to the structured log.
   *
   * Do not log req.body, authorization headers, cookies, or full URLs
   * because they may contain sensitive information.
   */
  customProps(req, res) {
    return {
      requestId: req.requestId ?? req.id,
      traceId: req.traceId ?? null,
      spanId: req.spanId ?? null,
      parentId: req.parentId ?? null,
      traceFlags: req.traceFlags ?? null,
      method: req.method,
      endPoint: req.url.split('?')[0] ?? '',
      statusCode: res.statusCode,
    };
  },

  /**
   * Serialize only safe error metadata.
   *
   * Avoid serializing arbitrary error objects because database/client
   * errors can contain sensitive query, connection, or request information.
   */
  customErrorObject(_req, _res, error) {
    return {
      err: {
        message: error.message,
        stack: error.stack,
        name: error.name,
      },
    };
  },

  /**
   * Never serialize complete request/response objects.
   *
   * This prevents accidental logging of:
   * - Authorization headers
   * - Cookies
   * - Request bodies
   * - Response headers
   * - PII
   */
  serializers: {
    req: () => undefined,
    res: () => undefined,
    // err: () => undefined,
  },
  customSuccessMessage: () => 'request completed',
  customErrorMessage: () => 'request failed',

  /**
   * Normalize pino-http's responseTime field to the application's
   * standard duration field.
   */
  formatters: {
    log(object: Record<string, unknown>) {
      if (object.responseTime !== undefined) {
        object.durationMs = object.responseTime;
        delete object.responseTime;
      }
      return object;
    },
  },
});
